/*
 * DIO_cnfg.c
 *
 *  Created on: Sep 22, 2019
 *      Author: Mohammed
 */


#include "DIO_cnfg.h"




DIO_cnfg_t DIO_cnfg_arr[NUM_OF_PINS] =
{
		{PORT_A,PIN2,INPUT,NA,PULLDOWN,INITIALIZED},
		{PORT_A,PIN4,INPUT,NA,PULLUP,INITIALIZED},
		{PORT_A,PIN6,OUTPUT,LOW,NA,INITIALIZED},
		
		//test LEDs for debugging//
		{PORT_D,PIN3,OUTPUT,LOW,NA,INITIALIZED},
		{PORT_D,PIN4,OUTPUT,LOW,NA,INITIALIZED},
		{PORT_D,PIN5,OUTPUT,LOW,NA,INITIALIZED},
		{PORT_D,PIN6,OUTPUT,LOW,NA,INITIALIZED},
		{PORT_D,PIN7,OUTPUT,LOW,NA,INITIALIZED},

		//  7-SEG 4 PINS //
		        {PORT_B,PIN0,OUTPUT,LOW,NA,INITIALIZED},
				{PORT_B,PIN1,OUTPUT,LOW,NA,INITIALIZED},
				{PORT_B,PIN2,OUTPUT,LOW,NA,INITIALIZED},
				{PORT_B,PIN3,OUTPUT,LOW,NA,INITIALIZED},

};

