/*
 * TIMER_cnfg.c
 *
 *  Created on: Sep 24, 2019
 *      Author: Mohammed
 */

#include "TIMER_cnfg.h"



TIMER_cnfg_t TIMER_cnfg_arr[NUM_OF_TIMER] =
{
		{TIMER0,PRESCALER0,NORMAL_MODE,NORMAL,INTERRUPT,NA,INITIALIZED },
		{TIMER1,PRESCALER0,NORMAL_MODE,NORMAL,INTERRUPT,ICU_NO_USED,INITIALIZED },
		{TIMER2,PRESCALER0,NORMAL_MODE,NORMAL,INTERRUPT,NA,INITIALIZED }
};
