/*
 * TIMER_cnfg.c
 *
 *  Created on: Sep 24, 2019
 *      Author: Mohammed
 */

#include "TIMER_cnfg.h"



TIMER_cnfg_t TIMER_cnfg_arr[NUM_OF_TIMERS] =
{
		{TIMER0,CTC_MODE,TOGGLE,NO_INTERRUPT,NA,PRESCALER1024 ,NOT_INITIALIZED},	// Solved test case Passed
<<<<<<< HEAD
		{TIMER1,NORMAL_MODE,TOGGLE,NO_INTERRUPT,NO_ICU_USED,PRESCALER1024 ,INITIALIZED},
		{TIMER2,CTC_MODE,TOGGLE,NO_INTERRUPT,NA,PRESCALER1024 ,NOT_INITIALIZED}

=======
		{TIMER1,NORMAL_MODE,TOGGLE,NO_INTERRUPT,ICU_NO_USED,PRESCALER1024 ,INITIALIZED},		
		{TIMER2,CTC_MODE,TOGGLE,NO_INTERRUPT,NA,PRESCALER1024 ,NOT_INITIALIZED}		
				
>>>>>>> 01ddf6f6e03651ea8ba47a3da74c4c67ff775f65
};
